### PR TITLE
Restore compatibility with PHP 7.4 by fixing regular expressions

### PR DESCRIPTION
**Pull request by alexanderharm**
I upgraded simplehtmldom to the latest stable version since it contained illegal regular expressions (`-` in character class not escaped). I also added some minor fixes to the regular expressions used in plugin-code. I will try and bump PHPWord as well in the coming days since it parses HTML natively and is quite outdated.

### CODE REVIEW

**Comment by Fasse** [comment]
Your pull request has 138 files changed. That sounds a litte bit to much. 

The examples und manual should be removed and not delivered through this plugin.

**Review by Fasse — CHANGES_REQUESTED** [review]
Your pull request has 138 files changed. That sounds a litte bit to much.

The examples und manual of simplehtmldom should be removed and not delivered through this plugin.

**Comment by alexanderharm** [comment]
I thought so initially but then the original plugin shipped them as well. Removed and only kept license, class and changelog.

**Review by Fasse — COMMENTED** [review]
Have you test the plugin with the updated library?

**Review by Fasse — APPROVED** [review]

**Comment by alexanderharm** [comment]
Yes, in v4-beta3 and the latest 3.x

**Comment by alexanderharm** [comment]
Do you publish both versions (for 3.x and 4.x) from master? Couldn't find corresponding tags or branches...

**Comment by Fasse** [comment]
No, in this repository there are no tags or branches. Therefore it's not possible to publish version 3.x from this.

Could you send me the 3.x plugin. I will then publish it on our homepage.

**Comment by alexanderharm** [comment]
[written_communications_3.3.2.zip](https://github.com/thomas-rcv/admidio-written_communications/files/5542916/written_communications_3.3.2.zip)
[written_communications_3.2.2.zip](https://github.com/thomas-rcv/admidio-written_communications/files/5542917/written_communications_3.2.2.zip)

- v3.x -> 3.2.2
- v4.x -> 3.3.2

**Comment by Fasse** [comment]
Thank you very much for your work. I have updated the plugin page.

**Pull request merged**
